### ISSUE TITLE
Data transfer costs?

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/proposal#2]
Shouldn't data transfer also be included in the cost estimates?

PS. Great proposal.

**Comment by gaborcsardi** [comment]
For most providers internal transfer is free.

Non-internal transfer will not cost much, probably. Uploading or getting the packages from GitHub is not a lot of traffic, even for many builds. Downloading the packages from the r-hub repo is probably also not too much, at least in the first year(s), as it'll be probably much less used than CRAN. Plus there is the website, that is also not a lot.

It is true that we might need to re-evaluate in 1-3 years, but that is true for all r-hub services and costs.
