### ISSUE TITLE
use gitlab for CI?

### ISSUE THREAD

**Issue by jangorecki** [r-hub/proposal#6]
I just read the proposal and it seems you are going to reimplement a lot of what gitlab did.
gitlab is a open-source github alternative, it has CI which work on docker. The _runners_ (e.g. docker images) runs the job obtained from CI server which is shipped with gitlab platform.

> Make it possible for organizations and individuals to contribute (the cost of) machines to the build farm.

_Runners_ are pluggable, contribution with machines seems to be pretty straightforward.
You can try to plug your own _runner_ into gitlab**.com** CI server and execute builds on it, I haven't tried that.

> Make services reproducible. It should be possible to start up an instance of any r-hub service within minutes, for anyone, even on their own laptop. This is crucial for development, testing and user contribution.

There is already gitlab docker image available so making r-hub as service from docker images should be doable as well.

I believe you don't need to host gitlab website to use it's CI.
I was able to setup CI process for R package on gitlab**.com**: https://gitlab.com/jangorecki/r.gitlab.ci and also locally hosted gitlab + CI.
~~Runner docker image must have `git` installed, but this limitation will likely be removed in future.~~

**Comment by gaborcsardi** [comment]
Thanks, looks like the GitLab CI has improved a lot since I last time looked it. 

Unfortunately it seems that you need to host gitlab as well, to get the CI: https://gitlab.com/gitlab-org/gitlab-ce/blob/8-0-stable/doc/migrate_ci_to_ce/README.md

It would be actually great to replace Jenkins with something more lightweight, but I don't know any multiplatform alternatives.

**Comment by gaborcsardi** [comment]
Btw. I don't want to reimplement GitLab or any other CI. Thanks for reminding me not to do that! 

Essentially I will take an existing CI (Jenkins for now) and build around it, so that it is friendlier to R users. Personally I would not mind using something else than Jenkins, but I currently don't see any alternatives. I'll keep an eye on the GitLab CI, though.

**Comment by jangorecki** [comment]
I was just reading gitlab-ci feature to produce _artifacts_ (e.g. pdf reports at the end of CI) and found that:

> the Windows shell executor does not currently support artifact uploads

that would mean the windows is supported platform (excluding that particular feature) if can allow shell access.

http://doc.gitlab.com/ee/ci/yaml/README.html#artifacts

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by cboettig** [comment]
Gabor, have you taken a look a http://GitHub.com/drone/drone for CI
infrastructure?

On Fri, Jan 22, 2016, 4:35 PM Gábor Csárdi notifications@github.com wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/r-hub/proposal/issues/6#issuecomment-174098294.
> 
> ## 

http://carlboettiger.info

**Comment by eddelbuettel** [comment]
Looks interesting. Are you using it yet?

**Comment by gaborcsardi** [comment]
Drone is Linux-only, so it is not ideal for r-hub. 

I wanted to support their public CI with r-builder, but they have a time limit, so I cannot build R on their system, and they never responded to my emails.

**Comment by cboettig** [comment]
Sounds like you are referring to the hosted version, not the drone code
base itself?  It is similar to gitlab in giving you a self hosted system, I
use it all the time from my own server when i need a ci system without
timeouts.

There aim is to be a industry wide replacement for Jenkins. Development is
very active and I've found the gitter and issues trackers very responsive
to my off-the-wall questions.

I dunno about supporting Mac & windows builds....

On Sat, Jan 23, 2016, 1:46 AM Gábor Csárdi notifications@github.com wrote:

> Drone is Linux-only, so it is not ideal for r-hub.
> 
> I wanted to support their public CI with r-builder, but they have a time
> limit, so I cannot build R on their system, and they never responded to my
> emails.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/r-hub/proposal/issues/6#issuecomment-174166238.
> 
> ## 

http://carlboettiger.info

**Comment by jangorecki** [comment]
According to [advanced-configuration.md#the-shells](https://github.com/ayufan/gitlab-ci-multi-runner/blob/master/docs/configuration/advanced-configuration.md#the-shells) two windows shells should be available.

```
       cmd  |   generate Windows Batch script. All commands are executed in Batch context (default for Windows)
powershell  |   generate Windows PowerShell script. All commands are executed in PowerShell context
```

docs for windows runner for CI jobs: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/windows.md

---

Some additional note on gitlab CI features for R ecosystem.
GitLab gets gitlab-pages feature recently, which appears to be more powerful than github-pages, because you define a job to produce a web pages - you can use knitr or rmarkdown (or even `echo '<html>...</html>' > index.html`). In general you are free to build any dependency just to produce `public` directory content.
I've just tested that, and during my CI workflow for build & check, I was additionally able to host drat repository, host manuals as html pages and a homepage. This is quite minimal example, you can get much more flexibility with knit, knit_rd, rmarkdown.
1. gl-pages website: [jangorecki.gitlab.io/data.table](http://jangorecki.gitlab.io/data.table/)
2. gl-pages _artifacts_ produced by `pages` job for project: [gitlab.com/jangorecki/data.table/builds/640724/artifacts/browse/public/](https://gitlab.com/jangorecki/data.table/builds/640724/artifacts/browse/public/)
3. definition [.gitlab-ci.yml](https://gitlab.com/jangorecki/data.table/blob/737ba55704d85eb953192d953eaf2c365df5d4e7/.gitlab-ci.yml)

It should be also possible to build vignettes and probably even straightforward using docker hadleyverse or ropensci images. So gitlab could handle not just cross platform _check_ but also serve documentation, drat repositories and vignettes.

**examples updated on 20160202**
