### ISSUE TITLE
External spatial libraries

### ISSUE THREAD

**Issue by mdsumner** [r-hub/proposal#7]
Does r-hub intend to support a wider range of external libraries for CRAN? The ones that are particularly problematic from my perspective are file format libraries used by GDAL and NetCDF, in turn used by rgdal and raster and ncdf4: 

HDF4
HDF5
NetCDF(-3)
NetCDF-4

These aren't available in Windows binary builds for rgdal, and only NetCDF(-3) is available for ncdf and RNetCDF (these packages _can_ be built and used with NetCDF-4).  The package ncdf4 is not on CRAN for Windows. 

I believe that CRAN uses a cross-compiler approach for rgdal, building the Windows binary on Linux - but I'm not sure about the NetCDF specific packages. 

The rgdal package is vastly more powerful from my perspective when it has access to these format drivers, and more and more providers are serving NetCDF-4 only these days - mostly I'm talking about remote sensing data, but it's a very wide range of data sources beyond that. 

Having this stuff in Windows, without needing to compile these external libraries into GDAL and then into rgdal yourself, would be awesome. 

Thank you, I'm very happy to flesh out details and requirements if this is a possibility for r-hub. There are many other formats that rgdal can leverage as well. Some combinations of drivers do clash and so it might be needed to have multiple rgdal builds on Windows, for example the OpenDAP driver and HTTP drivers cannot be differentiated between a raw .jpg URL and a Thredds server - this can be controlled by environment variables, but still there might be other reasons for multiple builds. 

Urbanek's recipes project has similar support, so perhaps that is being considered here? 

https://github.com/s-u/recipes

Cheers, Mike.

**Comment by gaborcsardi** [comment]
Once we are up and running, I can look into packages requiring special treatment, sure.
If you have experience with compiling HDFx and NetCDFx on/for windows, then with your help it shouldn't be a problem to support them on r-hub.

**Comment by mdsumner** [comment]
Great thanks! I only just noticed the announcement that it's now public, congratulations!
