### ISSUE TITLE
supporting 'suites' of packages for co-testing, or testing against 'preview' versions of packages

### ISSUE THREAD

**Issue by skyebend** [r-hub/proposal#8]
First, I'm really excited to see this proposal!  The statnet team has had to build our own infrastructure for testing nightly builds and release candidates on multiple platforms.  It is fragile and PITA to maintain, so being able to migrate to a system like this would be wonderful.   

One issue we run into which I don't think I've seen addressed here is when we need to make complementary changes to multiple packages.   The simplest case is when a change causes a test in a reverse-Depending package to fail and I need to check that the fix is correct.   More complex is when refactoring requires coordinated changes in two closely related packages.  

In our system, we handle this roughly by  suites of release candidate versions that should be built together.  Seems like a possible solution would be setting up a configuration system that would allow testing against r-hub hosted versions of packages that are not yet deployed to CRAN.   This would also be very helpful for the situations where I receive notifications about an issue due to soon-to-be-deployed changes in a package mine Depends on.  I'd need to be able to say "check my package against the most recent CRAN versions, but for package A, use the R-hub preview release".

Maybe a possible mechanism would be for each R-hub package build to have a url that conforms to a repository structure, and the hierarchy of CRAN mirrors could be set before  package setup to ensure that the preview versions are downloaded from the appropriate R-hub urls, with the remainder defaulting to CRAN?

**Comment by gaborcsardi** [comment]
Hello, I believe this is already supported via the `Remotes` mechanism, see https://cran.rstudio.com/web/packages/devtools/vignettes/dependencies.html

**Comment by eddelbuettel** [comment]
You do not need devtools fot this.  Just set up a repository (and [drat](http://dirk.eddelbuettel.com/code/drat.html) makes it trivial) and point to it from `DESCRIPTION` via Additional_Repositories.  That us allowed by CRAN and used.

**Comment by gaborcsardi** [comment]
@eddelbuettel Yes, that's another way. They have pros and cons I believe.

You do not need devtools for `Remotes`, either, just add the `Remotes` field, and r-hub will use it automatically. It'll also use `Additional_Repositories` if you choose to go that way.

**Comment by eddelbuettel** [comment]
Good to know, and thanks for the clarification.

**Comment by skyebend** [comment]
Seems like the `Remotes` /  `Additional_Repositories` mechanism will work fine, but perhaps a little messy since the temporary directives will be part of the packages that are being tested so will have to edit DESCRIPTION after testing and ensure that version with Remotes doesn't remain in the wild pointing to branch that will go away or never be updated.  I guess the workflow for packages A Depending on  B and a bug fix that requires changes to both A and B would be:
- fork A_bugfix on github
- fork B_bugfix on github
- set A's Remotes to point to B_bugfix
- commit fixes to A_bugfix and B_bugfix
- email revdep maintainers with links to A_bugfix and B_bugfix  if they need to update and test
- submit B_bugfix to CRAN
- remove A's Remotes line and increment minor version number (so it will replace any earlier versions that revdeps used for testing that may still have the Remotes lines) 
- submit A_bugfix to CRAN

Does that seem correct?  Perhaps I'm making this needlessly complicated. This has certainly happed to us, but likely the use case is fairly rare.

**Comment by gaborcsardi** [comment]
If you don't want to, then you don't need to fork (btw. by "fork" I assume you mean branch), you can just refer to a commit id in the original tree.
